# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ETqRfGbYpRJAS5DR5WzFq2NJ5-tKHvT
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

df = pd.read_csv("IRIS.csv")

df.head()

df.describe()

sns.pairplot(df, hue="species")
plt.show()

x = df.drop("species", axis=1)
x

y = df["species"]
y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

x_test.head(2)

new_data = pd.DataFrame({"sepallength":[6.7],"sepalwidth":6.5,"petallength":3.4,"petalwidth":2.9})

prediction = knn.predict(new_data)

prediction[0]

df.iloc[100:]

