# -*- coding: utf-8 -*-
"""shopper_sentiments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14k6WTmF-5eRP-7jq-DNksnwyhK2lI8id
"""

import plotly.express as px
import pandas as pd
import numpy as np

import pandas as pd

# Try reading the file with a different encoding, for example 'latin-1'
df = pd.read_csv("shopper.csv", encoding='latin-1')

df

df.head()

df.info()

df.describe()

df.isnull()

df.isnull().sum()

df.columns

df.shape

fig1 = px.histogram(df, x='review-label', title='Distribution of Ratings')
fig1.show()

fig2 = px.bar(df.groupby(['year', 'month']).size().reset_index(name='count'),
              x='month', y='count', color='year',
              title='Monthly Review Count Over the Years')
fig2.show()

fig3 = px.scatter_geo(df, lat='latitude', lon='longitude', color='review-label',
                      title='Geospatial Distribution of Reviews')

fig3.show()

